export const SET_USER = "SET_USER";

export const GET_GIST_LIST = "GET_GIST_LIST";
export const GET_GIST_LIST_SUCCESS = "GET_GIST_LIST_SUCCESS";
export const GET_GIST_LIST_FAIL = "GET_GIST_LIST_FAIL";

export const GET_GIST_DETAIL = "GET_GIST_DETAIL";
export const GET_GIST_DETAIL_FAIL = "GET_GIST_DETAIL_FAIL";
export const GET_GIST_DETAIL_SUCCESS = "GET_GIST_DETAIL_SUCCESS";
